spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.application.name=usuario-service
server.port=${USUARIO_SERVICE_PORT:3004}

spring.datasource.url=jdbc:postgresql://${USUARIO_DB_HOST:localhost}:${USUARIO_DB_PORT:5432}/${USUARIO_DB_NAME:usuario_db}
spring.datasource.username=${USUARIO_DB_USER:postgres}
spring.datasource.password=${USUARIO_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

logging.level.root=${LOG_LEVEL:INFO}
logging.level.usuarioService.usuario_service=${LOG_LEVEL:INFO}
logging.file.name=../logs/usuario-service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] %msg%n

server.tomcat.basedir=..
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.prefix=usuario-service-access
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.pattern=%t %m %U %s %Dms
